### ISSUE TITLE
App menu buttons on second monitor panel don't play nicely with other extensions

### ISSUE THREAD

**Issue by killarny** [darkxst/multiple-monitor-panels#5]
Extensions that modify the app menu button (such as [Window Options](https://bitbucket.org/mathematicalcoffee/window-options-gnome-shell-extension) or [StatusTitleBar](https://github.com/emerinohdz/StatusTitleBar)) don't carry over to the second button this extension is creating.

From what I've read about the method the Window Options extension is using, when the new app menu button has a `_focusApp` property, then it should be able to hook into your new button. I don't know if other extensions that modify the app menu button use a similar approach.

**Comment by darkxst** [comment]
Interoperability between extensions is always a bit of a pain. They would need to be dealt with on a case-by case basis. And there is always the issue that extension load order is undefined.

Having a quick look at the extensions that you listed:
**Window Options** - This one should be relatively straight forward. Basically it just needs to be patched to search the extra panels that I create with my extensions.

**Status TitleBar** - This one will be tricky. Since it is patching the same functions as we are, this will conflict. It may be easiest to just incorporate similar functionality into my extension.

**Comment by killarny** [comment]
I'll be happy to comment on the existing compatibility ticket on Window Options tracker to point the dev in this direction.

As far as the Status Titlebar extension, I remember seeing somewhere that he doesn't have much time to spend on his extension anymore, so integrating it into yours would be really cool. I'd be willing to attempt to help - I'm fairly proficient with js, but I've never looked into gnome extensions before.

**Comment by darkxst** [comment]
ok, the extra panels are created in `Main.__eP.panels[monitor_index]`
However I also provide an array with direct access to all the appMenu objects I create `Main.panel._appMenus[monitor_index]`
It would be sufficient to iterate through that array and apply patches to each

```
if (Main.panel._appMenus !== undefined)
    patch each menu in Main.panel._appMenus[]
else
    run existing search code to find appMenu on primary panel.
```

**Comment by darkxst** [comment]
Most of the code in Status Titlebar appears to be cut+pasted from appMenu.js. So you would need to identify the code that isnt and merge that into the multiple panels extension. Of course it should be optional, so would also need to add a schema setting for it and hook it up in `prefs.js`.

**Comment by mathematicalcoffee** [comment]
Hi - I wrote the window-options extension & have done a bit of work on the StatusTitleBar to get it to GNOME 3.4.

I've also been thinking about how to make these all play nicely with each other. The main problem is that each extension needs to know what an "app menu button" is to be able to patch it. It'd be nice to simply loop through objects in the panel and check if `testButton instanceOf Panel.AppMenuButton`, and if so, patch it.

However STB defines a new AppMenuButton class that does not inherit from Panel.AppMenuButton, so (for example) Window Options won't know that it is an app menu button. Hence it searches for any button with a '_focusApp' property and assumes that to be AppMenuButton-ish.

However at the moment Window Options has to _explicity_ listen for STB being loaded to force a re-scan for the new app menu button (because STB does not update `Main.panel._appMenu` which is what I'd usually use to determine what the "app menu button" is). This breaks the extension barrier (it'd be nice if W-O didn't have to hard-code a "if StatusTitleBar is loaded:" statement...)

I have a few thoughts on how to fix compatibility with all the extensions, but they all involve breaking the extension barrier in some way (i.e. one or more extension is explicitly aware of objects created by the other):
- STB _patches_ Panel.AppMenuButton rather than creating its own class (that way `testbutton instanceof Panel.AppMenuButton` will be a good test for what is the app menu button)
- In MMP, since NewAppMenuButton inherits from AppMenuButton it gets the title-displaying ability by default (ahh, but NewAppMenuButton overrides _sync which STB uses to display the window title??)
- W-O simply scans for any `instanceof Panel.AppMenuButton` to patch.

**BUT**: How will W-O know that there are multiple app menu buttons in existence? It will have to break the extension barrier and listen for MMP being enabled (or perhaps just listen for Main.panel._appMenus being created)? Perhaps W-O should also patch Panel.AppMenuButton.prototype to add the menu ???

(There really needs to be some system whereby global objects such as the panel/appMenu each have a controller, and each extension may request that a change be done to the global object. Then the controller tries to queue them all to prevent each extension from overwriting the effects of the previous ones...)

One other thing I can think of is if I rewrite STB to not have to override _any_ functions from the original AppMenuButton (except perhaps `_init`), in which case any subclass of AppMenuButton will get the STB changes without having to worry about leaving (e.g.) the `_sync` function alone?

And to confirm @darkxst STB is cut and paste from AppMenuButton in panel.js with a few changes - I have the list of changes if you are interested.

Anyhow I'll keep thinking about how to make the extensions compatible without breaking the extension barrier too much, but I have my finger in too many pies at the moment so really have not enough time to give more love to W-O :(  (Need to take a holiday so I have time to work on extensions again!)

**Comment by darkxst** [comment]
It really is a limitation of the current extension system, that as soon as 2 extensions start messing around with the same objects they will conflict. At this point it becomes very hard to do anything without breaking your so called `extension barrier`. 

Indeed for STB it should be quite trivial to implement without overriding the exisiting functions, perhaps using a signal hooked up on the 'changed' signal, to update the title. Then it should just work with MMP, provided that the extensions load in the correct order.

I suppose something similar could be possible for W-O, however I am not sure how you would have 2 different extensions injecting code into `_init`.
